<a href="https://colab.research.google.com/github/notmylove/blogs/blob/master/tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

建立一个最简单的神经网络模型，通过**tf.keras.Sequential()**函数

layers表示层数，neuron表示神经元，本文模型里的layer为1，neuron为1，输入数据的维数为一维
，通过model.compile()来进行编写模型的优化方法和损失函数，本文模型optimizer选择Stochastic gradient descend（随机梯度下降法），loss选择mean_squared_error（误差平方均值）

In [0]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error')

In [0]:
xs = np.arange(-1, 5, 1).astype(float)
ys = np.arange(-3, 9, 2).astype(float)
print(xs, '\n', ys)

[-1.  0.  1.  2.  3.  4.] 
 [-3. -1.  1.  3.  5.  7.]


In [0]:
xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)
print(xs, '\n', ys)

[-1.  0.  1.  2.  3.  4.] 
 [-3. -1.  1.  3.  5.  7.]


In [0]:
model.fit(xs, ys, epochs=500)


**epochs**表示模型训练时循环的周期，因为模型在训练时，首先会猜测一个拟合函数，根据正确的结果来计算这个猜测函数的损失函数，测量这个结果的好坏，然后根据所选的优化器来进行下一步的猜测，这个时候的猜测是基于要使损失函数最小，因此经过一次次的循环，最终损失函数是趋于收敛的。

In [0]:
a = model.predict([10, 11])
print(a)

[[18.98093 ]
 [20.978167]]


>Remember that neural networks deal with probabilities, so given the data that we fed the NN with, it calculated that there is a very high probability that the relationship between X and Y is $Y=2X-1$, but with only 6 data points we can't know for sure. As a result, the result for 10 and 11 is very close to 19 and 21, but not necessarily 19 and 21.